package com.cninfo.model;

public class VoiceInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_info.text_id
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    private Long textId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_info.voice_id
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    private Long voiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_info.text_path
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    private String textPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voice_info.voice_path
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    private String voicePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_info.text_id
     *
     * @return the value of voice_info.text_id
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public Long getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_info.text_id
     *
     * @param textId the value for voice_info.text_id
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public void setTextId(Long textId) {
        this.textId = textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_info.voice_id
     *
     * @return the value of voice_info.voice_id
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public Long getVoiceId() {
        return voiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_info.voice_id
     *
     * @param voiceId the value for voice_info.voice_id
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public void setVoiceId(Long voiceId) {
        this.voiceId = voiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_info.text_path
     *
     * @return the value of voice_info.text_path
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public String getTextPath() {
        return textPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_info.text_path
     *
     * @param textPath the value for voice_info.text_path
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public void setTextPath(String textPath) {
        this.textPath = textPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voice_info.voice_path
     *
     * @return the value of voice_info.voice_path
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public String getVoicePath() {
        return voicePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voice_info.voice_path
     *
     * @param voicePath the value for voice_info.voice_path
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    public void setVoicePath(String voicePath) {
        this.voicePath = voicePath;
    }
}