package com.cninfo.dao;

import com.cninfo.model.VoiceInfo;
import java.util.List;

public interface VoiceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_info
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    int deleteByPrimaryKey(Long textId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_info
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    int insert(VoiceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_info
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    VoiceInfo selectByPrimaryKey(Long textId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_info
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    List<VoiceInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice_info
     *
     * @mbg.generated Fri Feb 21 23:16:42 CST 2020
     */
    int updateByPrimaryKey(VoiceInfo record);
}